### ISSUE TITLE
Number of attempts

### ISSUE THREAD

**Issue by kckeiks** [Walentalien/Gesser-Game#1]
I want to play the game but I want it to display how many attempts it took me. 
Please implement this feature ASAP.

Thanks

**Comment by Walentalien** [comment]
Greetings,

We are delighted to inform you that your request has been successfully addressed! 🎉✨ The feature you envisioned—displaying the number of attempts taken during gameplay—has been elegantly integrated into the system. Now, as you embark on your gaming journey, you will have a clear view of your attempts, adding an extra layer of excitement and accomplishment to your experience.

We hope this enhancement elevates your enjoyment and adds a dash of competitive spirit to your playtime. Should you have any further requests or suggestions, please don't hesitate to share them with us.

Happy gaming and best of luck with your attempts! 🎮🚀

Warm regards,

Walentyn && Team
