### ISSUE TITLE
Limit number of attempts

### ISSUE THREAD

**Issue by kckeiks** [Walentalien/Gesser-Game#2]
It would make the game more challenging to limit the number of attempts per game.

* User passes max_attempts as a command line argument.
* If attempts > max_attempts, user loses.

**Options**
1. (Simple) Use https://doc.rust-lang.org/book/ch12-01-accepting-command-line-arguments.html.
2. (Fancy) Use [clap](https://docs.rs/clap/latest/clap/).

**Comment by Walentalien** [comment]
The issue has now been addressed using the simple method as outlined in the official Rust documentation for [accepting command-line arguments](https://doc.rust-lang.org/book/ch12-01-accepting-command-line-arguments.html).

The game now allows the user to pass the maximum number of attempts as a command-line argument. If the player exceeds the number of allowed attempts, he loses the game, and the program exits.

We are incredibly sorry for the delay in implementing this feature and appreciate your patience. Thank you for bringing this up, and we hope the game is more challenging and enjoyable with this new functionality!
